### ISSUE TITLE
Ability to add new Message Templates that can use tokens without modifying Nop code

### ISSUE THREAD

**Issue by Zyxious** [nopSolutions/nopCommerce#2935]
nopCommerce version: 4.00

Steps to reproduce the problem: 
It is fairly straight forward to add a new Message Template by SQL or code. While editing the template in admin I want to be able to use existing tokens. This can be done by adding a new case statement in the MessageTemplateExtensions.GetTokenGroups(...) method and specifying which tokens the template is allowed to use. All is good until I want to avoid touching nop code and putting the new message template in a plugin.

The problem is that MessageTemplateExtensions.GetTokenGroups(...) is a extension method of the MessageTemplate class and extension methods are static. I've yet to find a good way to override this behavior and thus I can not add new message templates that uses tokens and use them from a plugin without modifying nop code. 

A suggestion I have to solve this problem would be moving this message template - token group configuration to the database. Then it would be just as easy to configure this as creating a new message template.

**Comment by AndreiMaz** [comment]
done

**Comment by dealdiane** [comment]
I can't figure out why this is now marked as done. Sure there is no more extension method but the current implementation still doesn't allow us to create a custom `MessageTemplate` with a custom "Allowed message tokens" list without modifying the source code or overriding the default `IMessageTokenProvider` implementation. 

![image](https://user-images.githubusercontent.com/3430624/51284962-40e68380-1a52-11e9-8c96-e3972b034d6d.png)

Not very helpful for us who writes plugins and need to create custom `MessageTemplate`s

#3364 can be a simple solution and will not need new database tables.
