### ISSUE TITLE
The admin 'inline editor' has problems when the Value contains the " character (double quote)

### ISSUE THREAD

**Issue by noptools** [nopSolutions/nopCommerce#3922]
nopCommerce version:  4.20

Steps to reproduce the problem: 
Go to All Settings, search for the " character (double quote)
Note the setting | value
adminareasettings.lastnewstitleadminarea | "Powered by nopCommerce" link

then click Edit button, and you will see the value get truncated. (In this case, the truncation occurs at the first " char, so the resulting text is empty.  You can Edit the setting catalogsettings.pagesharecode, to see it truncates at the first " character)

This is happening because the <td> is getting converted from
   <td data-columnname="Value">"Powered by nopCommerce" link</td>
to
  <td data-columnname="Value">
     <input value= powered by nopcommerce" link" class="userinput" style="width: 99% ">
  </td>

If you Inspect the element and Edit as Html, it forms proper html like this, thus value is "":
<input value="" powered="" by="" nopcommerce"="" link"="" class="userinput" style="width: 99% ">

**Comment by noptools** [comment]
FYI ... When using the just released 4.20 no source, I was getting an odd error in the browser:
  Failed to load resource: the server responded with a status of 404 (Not Found)
  at c (jquery-1.10.2.min.js ...
So, I did a Ctrl-F5 to 'force browser refresh'...
Now, I don't have the inline editor truncate problem locally.  However, I did  Ctrl-F5 on the admin demo page
  http://admin-demo.nopcommerce.com/Admin/Setting/AllSettings
but I still see the problem there.

**Comment by BrettBaggott** [comment]
Pretty sure this issue was resolved with this commit:

https://github.com/nopSolutions/nopCommerce/commit/4f298517c02a61fc3e8bb3f52ce2ef730caa7bb8

**Comment by DmitriyKulagin** [comment]
> Pretty sure this issue was resolved with this commit:
> 
> [4f29851](https://github.com/nopSolutions/nopCommerce/commit/4f298517c02a61fc3e8bb3f52ce2ef730caa7bb8)

This fix will appear on the demo soon.

**Comment by noptools** [comment]
The editor still does not work right.  The " char no longer cause truncation,, but & and < and > do not work;  they show as &amp; &lt; and &gt;  in the input box, and get stored that way in the database table.

**Comment by DmitriyKulagin** [comment]
Closed #3922
