### ISSUE TITLE
calendar and datepicker and datetimepicker of Persian language

### ISSUE THREAD

**Issue by medallions** [nopSolutions/nopCommerce#5017]
Please apply the problem of displaying the calendar and datepicker and datetimepicker of Persian language history in Kendo library for version 4.40 once and for all. Good luck

Also see https://github.com/nopSolutions/nopCommerce/issues/3378, https://github.com/nopSolutions/nopCommerce/issues/3773

**Comment by medallions** [comment]
This issue was previously resolved in this* repository, but inconsistencies are observed in the latest version. Probably the root of the problem is caused by changing the technology to .netCore or changes in the hive library to version 2020.1.406.

*
https://github.com/Nosratian/KendoUI-Persian-Calendar

**Comment by medallions** [comment]
other respository for this issue in version 2018.1.221 :
https://github.com/CyberDepot/KendoUI_Gregorian-Persian-Hijri_Calendar-DatePicker-TimePicker

**Comment by medallions** [comment]
other respository for this issue only for NopCommerce Version 3.80 :
https://github.com/iPazooki/NopCommerce-PersianCalendar

if needed source of "bin/Persia.dll" in this respository I have it! .comment to Upload.thank you

**Comment by DmitriyKulagin** [comment]
Since we want to stop using the kendo library, this problem should be solved in issue # 5016

**Comment by exileDev** [comment]
Kendo doesn't support Hijri, Jalali calendars. So it's been postponed until we drop this lib.

Closed #5017

**Comment by medallions** [comment]
nopCommerce 4.50.2 And Kendo UI for jQuery R2 2022 Released ، But this problem was not solved for Persian language in nopCommerce.

**Comment by medallions** [comment]
last nopCommerce 4.50.3 And Kendo UI for jQuery R2 2022 Released ، But this problem was not solved for Persian language in nopCommerce....
